routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('part1');
});

Route::prefix('/part-1')->group(function () {
	Route::get('no-1', 'Part1Controller@calculateScore');
	Route::get('no-2/{string?}', 'Part1Controller@calculateLowercase');
	Route::get('no-3/{string?}', 'Part1Controller@parseString');
	Route::get('no-4', 'Part1Controller@showTable');
	Route::get('no-5/{string?}', 'Part1Controller@encrypt');
	Route::get('no-6/{string?}', 'Part1Controller@searchWord');
	
});

Route::prefix('/part-2')->group(function () {
	Auth::routes();

	// redirect to company list
	Route::get('/', function () {
	    return redirect()->route('company.index');
	});

	Route::middleware('auth')->group(function () {
		// company route
		Route::prefix('company')->name('company.')->group(function () {
			Route::get('/', 'Part2\CompanyController@index')->name('index');
			Route::get('create', 'Part2\CompanyController@create')->name('create');
			Route::post('store', 'Part2\CompanyController@store')->name('store');
			Route::get('edit/{id}', 'Part2\CompanyController@edit')->name('edit');
			Route::post('update', 'Part2\CompanyController@update')->name('update');
			Route::get('detail/{id}', 'Part2\CompanyController@show')->name('detail');
			Route::get('delete/{id}', 'Part2\CompanyController@destroy')->name('delete');
		});

		// employee route
		Route::prefix('employee')->name('employee.')->group(function () {
			Route::get('/', 'Part2\EmployeeController@index')->name('index');
			Route::get('create', 'Part2\EmployeeController@create')->name('create');
			Route::post('store', 'Part2\EmployeeController@store')->name('store');
			Route::get('edit/{id}', 'Part2\EmployeeController@edit')->name('edit');
			Route::post('update', 'Part2\EmployeeController@update')->name('update');
			Route::get('detail/{id}', 'Part2\EmployeeController@show')->name('detail');
			Route::get('delete/{id}', 'Part2\EmployeeController@destroy')->name('delete');
		});
	});
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $fillable = [
		'name',
		'email',
    	'logo',
    	'website',
    ];

    public function employees()
    {
        return $this->hasMany('App\Models\Employee');
    }
}

app/Http/Controllers/Part2/CompanyController.php
<?php

namespace App\Http\Controllers\Part2;

use App\Http\Controllers\Controller;
use App\Http\Requests\CompanyStoreRequest;
use App\Http\Requests\CompanyUpdateRequest;
use App\Models\Company;
use File;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['data'] = Company::withCount('employees')->latest()->paginate(5);

        return view('part2.company.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('part2.company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CompanyStoreRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyStoreRequest $request)
    {
        $post = $request->all();

        $filename = $post['name'] . " - " . time() . "." . $post['logo']->getClientOriginalExtension();
        $path = $post['logo']->storeAs('company', $filename);

        $company = new Company;
        $company->name    = $post['name'];
        $company->email   = $post['email'];
        $company->logo    = $path;
        $company->website = $post['website'];
        $company->save();

        $success = "Create company success";

        return redirect()->route('company.index')->withSuccess($success);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['data'] = Company::with('employees')->findOrFail($id);

        return view('part2.company.detail', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['data'] = Company::findOrFail($id);

        return view('part2.company.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  CompanyUpdateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function update(CompanyUpdateRequest $request)
    {
        $post = $request->all();

        $company = Company::findOrFail($post['id']);

        $old_image = $company->logo;     // old logo
        $path = $old_image;
        if (isset($post['logo'])) {
            $filename = $post['name'] . " - " . time() . "." . $post['logo']->getClientOriginalExtension();
            $path = $post['logo']->storeAs('company', $filename);

            if (File::exists( storage_path('app/' . $old_image) )) {
                // remove old image
                unlink(storage_path('app/' . $old_image));
            }
        }

        $company->name    = $post['name'];
        $company->email   = $post['email'];
        $company->logo    = $path;
        $company->website = $post['website'];
        $company->save();

        $success = "Update company success";

        return redirect()->route('company.index')->withSuccess($success);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::withCount('employees')->findOrFail($id);
        
        // check employee
        if ($company->employees_count > 0) {
            $error = ['Can not delete '. $company->name .', because it has employee(s).'];

            return redirect()->route('company.index')->withErrors($error);
        }

        $path = storage_path('app/' . $company->logo);
        if (File::exists($path)) {
            // remove image
            unlink($path);
        }
        $company->delete();

        $success = "Delete company success";

        return redirect()->route('company.index')->withSuccess($success);
    }
}

app/Http/Controllers/Part2/EmployeeController.php
<?php

namespace App\Http\Controllers\Part2;

use App\Http\Controllers\Controller;
use App\Http\Requests\EmployeeStoreRequest;
use App\Http\Requests\EmployeeUpdateRequest;
use App\Models\Company;
use App\Models\Employee;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['data'] = Employee::latest()->paginate(5);

        return view('part2.employee.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['companies'] = Company::orderBy('name')->get();

        return view('part2.employee.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  EmployeeStoreRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeStoreRequest $request)
    {
        $post = $request->all();

        $employee = new Employee;
        $employee->name       = $post['name'];
        $employee->email      = $post['email'];
        $employee->company_id = $post['company_id'];
        $employee->save();

        $success = "Create employee success";

        return redirect()->route('employee.index')->withSuccess($success);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['data'] = Employee::findOrFail($id);

        return view('part2.employee.detail', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['data'] = Employee::findOrFail($id);
        $data['companies'] = Company::orderBy('name')->get();

        return view('part2.employee.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  EmployeeUpdateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeUpdateRequest $request)
    {
        $post = $request->all();

        $employee = Employee::findOrFail($post['id']);
        $employee->name       = $post['name'];
        $employee->email      = $post['email'];
        $employee->company_id = $post['company_id'];
        $employee->save();

        $success = "Update employee success";

        return redirect()->route('employee.index')->withSuccess($success);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $employee = Employee::findOrFail($id);
        $employee->delete();

        $success = "Delete employee success";

        return redirect()->route('employee.index')->withSuccess($success);
    }
}

resources/views/part2/company/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="title">Create Company</div>
                    </div>
                </div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="row">
                        <div class="col-6">
                            <form method="POST" action="{{ route('company.store') }}" enctype="multipart/form-data">
                                @csrf

                                <div class="form-group">
                                    <label>Name *</label>
                                    <input type="text" class="form-control" name="name" value="{{ old('name') }}" required>
                                </div>
                                <div class="form-group">
                                    <label>Email *</label>
                                    <input type="email" class="form-control" name="email" value="{{ old('email') }}" required>
                                </div>
                                <div class="form-group">
                                    <label>Logo *</label>
                                    <p class="text-muted">Image ratio should be 1:1, min dimensions is 100x100 px, max size is 2 MB</p>

                                    <img id="preview" src="" width="100" height="100" class="mb-3 img-thumbnail hidden">

                                    <input id="logo" type="file" class="form-control-file" name="logo" value="{{ old('logo') }}" accept="image/png" required>
                                </div>
                                <div class="form-group">
                                    <label>Website *</label>
                                    <input type="text" class="form-control" name="website" value="{{ old('website') }}" placeholder="https://mysite.com" required>
                                </div>

                                <div class="mt-4">
                                    <a href="{{ url()->previous() }}" class="btn btn-outline-secondary mr-2">Cancel</a>
                                    <input type="submit" value="Save" class="btn btn-primary">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
    <script type="text/javascript">
        $(document).ready(function () {
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function(e) {
                        $('#preview').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(input.files[0]); // convert to base64 string
                }
            }

            $('#logo').change(function() {
                readURL(this);
                $('#preview').show();
            });
        });
    </script>
@endsection

resources/views/part2/company/detail.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="title">Detail Company</div>
                    </div>
                </div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-6">
                            <table class="custom-table">
                                <tbody>
                                    <tr>
                                        <td class="label">Name</td>
                                        <td class="semicolon">:</td>
                                        <td>{{ $data->name }}</td>
                                    </tr>
                                    <tr>
                                        <td class="label">Email</td>
                                        <td class="semicolon">:</td>
                                        <td>{{ $data->email }}</td>
                                    </tr>
                                    <tr>
                                        <td class="label">Logo</td>
                                        <td class="semicolon">:</td>
                                        <td>
                                            <img src="{{ asset('storage/app') .'/'. $data->logo }}" width="100" height="100">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label">Website</td>
                                        <td class="semicolon">:</td>
                                        <td>{{ $data->website }}</td>
                                    </tr>
                                    <tr>
                                        <td class="label">Employee(s)</td>
                                        <td class="semicolon">:</td>
                                        <td>
                                            @forelse($data->employees as $key => $employee)
                                                <div>{{ $employee->name }}</div>
                                            @empty
                                                -
                                            @endforelse
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                            
                            <div class="mt-4">
                                <a href="{{ url()->previous() }}" class="btn btn-outline-primary">Back</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/part2/company/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="title">Edit Company</div>
                    </div>
                </div>

                <div class="card-body">
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="row">
                        <div class="col-6">
                            <form method="POST" action="{{ route('company.update') }}" enctype="multipart/form-data">
                                @csrf
                                <input type="hidden" name="id" value="{{ $data->id }}">

                                <div class="form-group">
                                    <label>Name *</label>
                                    <input type="text" class="form-control" name="name" value="{{ old('name') ?? $data->name }}" required>
                                </div>
                                <div class="form-group">
                                    <label>Email *</label>
                                    <input type="email" class="form-control" name="email" value="{{ old('email') ?? $data->email }}" required>
                                </div>
                                <div class="form-group">
                                    <label>Logo</label>
                                    <p class="text-muted">Image ratio should be 1:1, min dimensions is 100x100 px, max size is 2 MB</p>
                                    
                                    <img id="preview" src="{{ asset('storage/app') .'/'. $data->logo }}" width="100" height="100" class="mb-3 img-thumbnail">

                                    <input id="logo" type="file" class="form-control-file" name="logo" value="{{ old('logo') ?? $data->logo }}" accept="image/png">
                                </div>
                                <div class="form-group">
                                    <label>Website *</label>
                                    <input type="text" class="form-control" name="website" value="{{ old('website') ?? $data->website }}" placeholder="https://mysite.com" required>
                                </div>

                                <div class="mt-4">
                                    <a href="{{ url()->previous() }}" class="btn btn-outline-secondary mr-2">Cancel</a>
                                    <input type="submit" value="Save" class="btn btn-primary">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
    <script type="text/javascript">
        $(document).ready(function () {
            function readURL(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function(e) {
                        $('#preview').attr('src', e.target.result);
                    }
                    reader.readAsDataURL(input.files[0]); // convert to base64 string
                }
            }

            $('#logo').change(function() {
                readURL(this);
            });
        });
    </script>
@endsection

resources/views/part2/company/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="title">Company</div>
                        <a href="{{ route('company.create') }}" class="btn btn-primary">Create</a>
                    </div>
                </div>

                <div class="card-body">
                    @if(session('success'))
                        <div class="alert alert-success" role="alert">
                            {{ session('success') }}
                        </div>
                    @endif
                    
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @isset($data)
                        @php
                            $current_page = $data->currentPage() - 1;
                            $per_page = $data->perPage();
                        @endphp

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th class="no">No</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Logo</th>
                                    <th>Last Modified</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($data as $key => $item)
                                    <tr>
                                        <td>{{ $current_page * $per_page + $key + 1 }}</td>
                                        <td>{{ $item->name }}</td>
                                        <td>{{ $item->email }}</td>
                                        <td>
                                            <img class="img" src="{{ asset('storage/app') .'/'. $item->logo }}" alt="Logo">
                                        </td>
                                        <td>{{ date('d-m-Y H:i:s', strtotime($item->updated_at)) }}</td>
                                        <td>
                                            <a href="{{ route('company.detail', $item->id) }}" class="btn btn-sm btn-outline-primary mr-2">Detail</a>
                                            
                                            <a href="{{ route('company.edit', $item->id) }}" class="btn btn-sm btn-info mr-2">Edit</a>

                                            @if($item->employees_count > 0)
                                                <a href="#" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#modal-has-employee">Delete</a>
                                            @else
                                                <a href="#" class="btn btn-sm btn-danger btn-delete"    data-link="{{ route('company.delete', $item->id) }}" data-name="{{ $item->name }}">Delete</a>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td class="text-center" colspan="6">No data available</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>

                        <div class="d-flex flex-row-reverse mt-5">
                            {{ $data->links() }}
                        </div>
                    @endisset
                </div>
            </div>
        </div>
    </div>

    {{-- modal has employee --}}
    <div class="modal fade" id="modal-has-employee" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Can't Delete</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div>Can not delete this company, because it has employee(s).</div>
                    <div>Please delete the employee(s) first.</div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    {{-- modal confirm delete --}}
    <div class="modal fade" id="modal-confirm-delete" tabindex="-1" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Confirm Delete</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Are you sure want to delete <b id="delete-name"></b>?</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Cancel</button>
                    <a href="#" id="btn-confirm-delete" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('js')
    <script type="text/javascript">
        $(document).ready(function () {
            // assign delete url & company name
            $('.btn-delete').on('click', function () {
                var link = $(this).data("link");
                var name = $(this).data("name");

                $('#delete-name').text(name);
                $('#btn-confirm-delete').attr('href', link);

                // show the modal
                $('#modal-confirm-delete').modal('show');
            });

            // remove delete url & company name when modal hidden
            $('#modal-confirm-delete').on('hidden.bs.modal', function (e) {
                $('#delete-name').text('');
                $('#btn-confirm-delete').attr('href', '#');
            });
        });
    </script>
@endsection