routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('part1');
});

Route::prefix('/part-1')->group(function () {
	Route::get('no-1', 'Part1Controller@calculateScore');
	Route::get('no-2/{string?}', 'Part1Controller@calculateLowercase');
	Route::get('no-3/{string?}', 'Part1Controller@parseString');
	Route::get('no-4', 'Part1Controller@showTable');
	Route::get('no-5/{string?}', 'Part1Controller@encrypt');
	Route::get('no-6/{string?}', 'Part1Controller@searchWord');
	
});

Route::prefix('/part-2')->group(function () {
	Auth::routes();

	// redirect to company list
	Route::get('/', function () {
	    return redirect()->route('company.index');
	});

	Route::middleware('auth')->group(function () {
		// company route
		Route::prefix('company')->name('company.')->group(function () {
			Route::get('/', 'Part2\CompanyController@index')->name('index');
			Route::get('create', 'Part2\CompanyController@create')->name('create');
			Route::post('store', 'Part2\CompanyController@store')->name('store');
			Route::get('edit/{id}', 'Part2\CompanyController@edit')->name('edit');
			Route::post('update', 'Part2\CompanyController@update')->name('update');
			Route::get('detail/{id}', 'Part2\CompanyController@show')->name('detail');
			Route::get('delete/{id}', 'Part2\CompanyController@destroy')->name('delete');
		});

		// employee route
		Route::prefix('employee')->name('employee.')->group(function () {
			Route::get('/', 'Part2\EmployeeController@index')->name('index');
			Route::get('create', 'Part2\EmployeeController@create')->name('create');
			Route::post('store', 'Part2\EmployeeController@store')->name('store');
			Route::get('edit/{id}', 'Part2\EmployeeController@edit')->name('edit');
			Route::post('update', 'Part2\EmployeeController@update')->name('update');
			Route::get('detail/{id}', 'Part2\EmployeeController@show')->name('detail');
			Route::get('delete/{id}', 'Part2\EmployeeController@destroy')->name('delete');
		});
	});
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('public/js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('public/css/app.css') }}" rel="stylesheet">

    <style type="text/css">
        .main{
            margin-top: 3.5rem;
        }
        .title{
            font-size: 18px;
        }
        .table .no{
            width: 50px;
        }
        .table .img{
            max-width: 50px;
            max-height: 50px;
        }
        .custom-table td{
            vertical-align: top;
            padding: 3px 5px;
        }
        .custom-table .label{
            min-width: 100px;
            font-weight: bold;
        }
        .custom-table .semicolon{
            width: 20px;
        }
        .hidden{
            display: none;
        }
    </style>

    @yield('css')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    @auth
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('company.index') }}">Company</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('employee.index') }}">Employee</a>
                        </li>
                    </ul>
                    @endauth

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="main py-4">
            @yield('content')
        </main>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    @yield('js')
</body>
</html>